
CREATE TABLE IF NOT EXISTS DEV_ICESI.SYSTEM_RECOMMENDATION.CONAGUA_WEATHER_RAW (
    NMUN STRING,
    DESCIEL STRING,
    DH NUMBER,
    DIRVIENC STRING,
    DIRVIENG NUMBER,
    DPT NUMBER,
    DSEM STRING,
    HLOC TIMESTAMP,
    HR NUMBER,
    IDES NUMBER,
    IDMUN NUMBER,
    LAT FLOAT,
    LON FLOAT,
    NES STRING,
    NHOR NUMBER,
    PREC FLOAT,
    PROBPREC FLOAT,
    RAF FLOAT,
    TEMP FLOAT,
    VELVIEN FLOAT
);
