COPY INTO RAW_DATA.CONAGUA_WEATHER.CONAGUA_WEATHER_RAW
FROM '@RAW_DATA.CONAGUA_WEATHER.STAGE_RAW_DATA/weather_data_{{params.dt}}.csv'
FILE_FORMAT = (TYPE = 'CSV', FIELD_OPTIONALLY_ENCLOSED_BY = '"', SKIP_HEADER = 1);